"use strict";

export const [
  a,
  abbr,
  acronym,
  address,
  applet,
  area,
  article,
  aside,
  audio,
  b,
  base,
  basefont,
  bdi,
  bdo,
  big,
  blockquote,
  body,
  br,
  button,
  canvas,
  caption,
  center,
  cite,
  code,
  col,
  colgroup,
  data,
  datalist,
  dd,
  del,
  details,
  dfn,
  dialog,
  dir,
  div,
  dl,
  dt,
  em,
  embed,
  fieldset,
  figcaption,
  figure,
  font,
  footer,
  form,
  frame,
  frameset,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  head,
  header,
  hr,
  html,
  i,
  iframe,
  img,
  input,
  ins,
  kbd,
  label,
  legend,
  li,
  link,
  main,
  map,
  mark,
  meta,
  meter,
  nav,
  noframes,
  noscript,
  object,
  ol,
  optgroup,
  option,
  output,
  p,
  param,
  picture,
  pre,
  progress,
  q,
  rp,
  rt,
  ruby,
  s,
  samp,
  script,
  section,
  select,
  small,
  source,
  span,
  strike,
  strong,
  style,
  sub,
  summary,
  sup,
  svg,
  table,
  tbody,
  td,
  template,
  textarea,
  tfoot,
  th,
  thead,
  time,
  title,
  tr,
  track,
  tt,
  u,
  ul,
  video,
  wbr,
] = [
  "a",
  "abbr",
  "acronym",
  "address",
  "applet",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "basefont",
  "bdi",
  "bdo",
  "big",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "center",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "dir",
  "div",
  "dl",
  "dt",
  "em",
  "embed",
  "fieldset",
  "figcaption",
  "figure",
  "font",
  "footer",
  "form",
  "frame",
  "frameset",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hr",
  "html",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "kbd",
  "label",
  "legend",
  "li",
  "link",
  "main",
  "map",
  "mark",
  "meta",
  "meter",
  "nav",
  "noframes",
  "noscript",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "param",
  "picture",
  "pre",
  "progress",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "script",
  "section",
  "select",
  "small",
  "source",
  "span",
  "strike",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "svg",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "tt",
  "u",
  "ul",
  "video",
  "wbr",
];

export const domTypes = {
  canvas: HTMLCanvasElement,
  input: HTMLInputElement,
  div: HTMLDivElement,
  span: HTMLSpanElement,
  p: HTMLParagraphElement,
  h1: HTMLHeadingElement,
  h2: HTMLHeadingElement,
  h3: HTMLHeadingElement,
  h4: HTMLHeadingElement,
  h5: HTMLHeadingElement,
  h6: HTMLHeadingElement,
  ul: HTMLUListElement,
  li: HTMLLIElement,
  a: HTMLAnchorElement,
  button: HTMLButtonElement,
  form: HTMLFormElement,
  select: HTMLSelectElement,
  option: HTMLOptionElement,
  textarea: HTMLTextAreaElement,
  label: HTMLLabelElement,
  table: HTMLTableElement,
  thead: HTMLTableSectionElement,
  tbody: HTMLTableSectionElement,
  tfoot: HTMLTableSectionElement,
  tr: HTMLTableRowElement,
  th: HTMLTableCellElement,
  td: HTMLTableCellElement,
  img: HTMLImageElement,
  script: HTMLScriptElement,
  style: HTMLStyleElement,
  meta: HTMLMetaElement,
  link: HTMLLinkElement,
  header: HTMLHeadElement,
  footer: HTMLHeadElement,
  main: HTMLHeadElement,
  nav: HTMLHeadElement,
  section: HTMLHeadElement,
  article: HTMLHeadElement,
  aside: HTMLHeadElement,
  details: HTMLHeadElement,
  dialog: HTMLHeadElement,
  summary: HTMLHeadElement,
  progress: HTMLProgressElement,
  meter: HTMLMeterElement,
  audio: HTMLAudioElement,
  video: HTMLVideoElement,
  embed: HTMLEmbedElement,
  object: HTMLObjectElement,
  source: HTMLSourceElement,
  track: HTMLTrackElement,
  map: HTMLMapElement,
  area: HTMLAreaElement,
  svg: SVGSVGElement,
  path: SVGPathElement,
  circle: SVGCircleElement,
  ellipse: SVGEllipseElement,
  line: SVGLineElement,
  rect: SVGRectElement,
  polygon: SVGPolygonElement,
  polyline: SVGPolylineElement,
  text: SVGTextElement,
  tspan: SVGTSpanElement,
  defs: SVGDefsElement,
  use: SVGUseElement,
  symbol: SVGSymbolElement,
  g: SVGGElement,
  marker: SVGMarkerElement,
  linearGradient: SVGLinearGradientElement,
  radialGradient: SVGRadialGradientElement,
  stop: SVGStopElement,
  pattern: SVGPatternElement,
  clipPath: SVGClipPathElement,
  mask: SVGMaskElement,
  foreignObject: SVGForeignObjectElement,
  filter: SVGFilterElement,
  feBlend: SVGFEBlendElement,
  feColorMatrix: SVGFEColorMatrixElement,
  feComponentTransfer: SVGFEComponentTransferElement,
  feComposite: SVGFECompositeElement,
  feConvolveMatrix: SVGFEConvolveMatrixElement,
  feDiffuseLighting: SVGFEDiffuseLightingElement,
  feDisplacementMap: SVGFEDisplacementMapElement,
  feDistantLight: SVGFEDistantLightElement,
  feFlood: SVGFEFloodElement,
  feFuncA: SVGFEFuncAElement,
  feFuncB: SVGFEFuncBElement,
  feFuncG: SVGFEFuncGElement,
  feFuncR: SVGFEFuncRElement,
  feGaussianBlur: SVGFEGaussianBlurElement,
  feImage: SVGFEImageElement,
  feMerge: SVGFEMergeElement,
  feMergeNode: SVGFEMergeNodeElement,
  feMorphology: SVGFEMorphologyElement,
  feOffset: SVGFEOffsetElement,
  fePointLight: SVGFEPointLightElement,
  feSpecularLighting: SVGFESpecularLightingElement,
  feSpotLight: SVGFESpotLightElement,
  feTile: SVGFETileElement,
  feTurbulence: SVGFETurbulenceElement,
};